// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aiservice/internal/providers (interfaces: InkRecognizer,LLMClient)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/mocks/mock_providers.go github.com/aiservice/internal/providers InkRecognizer,LLMClient
//

// Package mocks is a generated GoMock package.
package mocks

// // MockInkRecognizer is a mock of InkRecognizer interface.
// type MockInkRecognizer struct {
// 	ctrl     *gomock.Controller
// 	recorder *MockInkRecognizerMockRecorder
// 	isgomock struct{}
// }

// // MockInkRecognizerMockRecorder is the mock recorder for MockInkRecognizer.
// type MockInkRecognizerMockRecorder struct {
// 	mock *MockInkRecognizer
// }

// // NewMockInkRecognizer creates a new mock instance.
// func NewMockInkRecognizer(ctrl *gomock.Controller) *MockInkRecognizer {
// 	mock := &MockInkRecognizer{ctrl: ctrl}
// 	mock.recorder = &MockInkRecognizerMockRecorder{mock}
// 	return mock
// }

// // EXPECT returns an object that allows the caller to indicate expected use.
// func (m *MockInkRecognizer) EXPECT() *MockInkRecognizerMockRecorder {
// 	return m.recorder
// }

// // RecognizeInk mocks base method.
// func (m *MockInkRecognizer) RecognizeInk(ctx context.Context, input models.InkInput) (models.TranscriptionResult, error) {
// 	m.ctrl.T.Helper()
// 	ret := m.ctrl.Call(m, "RecognizeInk", ctx, input)
// 	ret0, _ := ret[0].(models.TranscriptionResult)
// 	ret1, _ := ret[1].(error)
// 	return ret0, ret1
// }

// // RecognizeInk indicates an expected call of RecognizeInk.
// func (mr *MockInkRecognizerMockRecorder) RecognizeInk(ctx, input any) *gomock.Call {
// 	mr.mock.ctrl.T.Helper()
// 	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecognizeInk", reflect.TypeOf((*MockInkRecognizer)(nil).RecognizeInk), ctx, input)
// }

// // MockLLMClient is a mock of LLMClient interface.
// type MockLLMClient struct {
// 	ctrl     *gomock.Controller
// 	recorder *MockLLMClientMockRecorder
// 	isgomock struct{}
// }

// // MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
// type MockLLMClientMockRecorder struct {
// 	mock *MockLLMClient
// }

// // NewMockLLMClient creates a new mock instance.
// func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
// 	mock := &MockLLMClient{ctrl: ctrl}
// 	mock.recorder = &MockLLMClientMockRecorder{mock}
// 	return mock
// }

// // EXPECT returns an object that allows the caller to indicate expected use.
// func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
// 	return m.recorder
// }

// // Analyze mocks base method.
// func (m *MockLLMClient) Analyze(ctx context.Context, parts []*ai.Part) (models.SummarizeResponse, error) {
// 	m.ctrl.T.Helper()
// 	ret := m.ctrl.Call(m, "Analyze", ctx, parts)
// 	ret0, _ := ret[0].(models.SummarizeResponse)
// 	ret1, _ := ret[1].(error)
// 	return ret0, ret1
// }

// // Analyze indicates an expected call of Analyze.
// func (mr *MockLLMClientMockRecorder) Analyze(ctx, parts any) *gomock.Call {
// 	mr.mock.ctrl.T.Helper()
// 	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockLLMClient)(nil).Analyze), ctx, parts)
// }
