// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aiservice/internal/services/jobService (interfaces: Processor,JobStorage)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/mocks/mock_jobservice.go github.com/aiservice/internal/services/jobService Processor,JobStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/aiservice/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockProcessor) Process(ctx context.Context, req models.AnalyzeRequest) (models.SummarizeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, req)
	ret0, _ := ret[0].(models.SummarizeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockProcessorMockRecorder) Process(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProcessor)(nil).Process), ctx, req)
}

// MockJobStorage is a mock of JobStorage interface.
type MockJobStorage struct {
	ctrl     *gomock.Controller
	recorder *MockJobStorageMockRecorder
	isgomock struct{}
}

// MockJobStorageMockRecorder is the mock recorder for MockJobStorage.
type MockJobStorageMockRecorder struct {
	mock *MockJobStorage
}

// NewMockJobStorage creates a new mock instance.
func NewMockJobStorage(ctrl *gomock.Controller) *MockJobStorage {
	mock := &MockJobStorage{ctrl: ctrl}
	mock.recorder = &MockJobStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobStorage) EXPECT() *MockJobStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockJobStorage) Get(id string) (models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobStorageMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobStorage)(nil).Get), id)
}

// Save mocks base method.
func (m *MockJobStorage) Save(job models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockJobStorageMockRecorder) Save(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockJobStorage)(nil).Save), job)
}

// Update mocks base method.
func (m *MockJobStorage) Update(job models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobStorageMockRecorder) Update(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobStorage)(nil).Update), job)
}
