// Code generated by MockGen. DO NOT EDIT.
// Source: providers.go
//
// Generated by this command:
//
//	mockgen -source=providers.go -destination=./mocks/mock_providers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/aiservice/internal/models"
	providers "github.com/aiservice/internal/providers"
	ai "github.com/firebase/genkit/go/ai"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// GenerateTemplate mocks base method.
func (m *MockLLMClient) GenerateTemplate(ctx context.Context, parts []*ai.Part) (providers.TemplateGenerationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTemplate", ctx, parts)
	ret0, _ := ret[0].(providers.TemplateGenerationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTemplate indicates an expected call of GenerateTemplate.
func (mr *MockLLMClientMockRecorder) GenerateTemplate(ctx, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTemplate", reflect.TypeOf((*MockLLMClient)(nil).GenerateTemplate), ctx, parts)
}

// GenerateText mocks base method.
func (m *MockLLMClient) GenerateText(ctx context.Context, parts []*ai.Part) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateText", ctx, parts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateText indicates an expected call of GenerateText.
func (mr *MockLLMClientMockRecorder) GenerateText(ctx, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateText", reflect.TypeOf((*MockLLMClient)(nil).GenerateText), ctx, parts)
}

// GetName mocks base method.
func (m *MockLLMClient) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockLLMClientMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockLLMClient)(nil).GetName))
}

// ImageRecognition mocks base method.
func (m *MockLLMClient) ImageRecognition(ctx context.Context, parts []*ai.Part) (providers.ImageRecognitionFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageRecognition", ctx, parts)
	ret0, _ := ret[0].(providers.ImageRecognitionFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageRecognition indicates an expected call of ImageRecognition.
func (mr *MockLLMClientMockRecorder) ImageRecognition(ctx, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageRecognition", reflect.TypeOf((*MockLLMClient)(nil).ImageRecognition), ctx, parts)
}

// Structurize mocks base method.
func (m *MockLLMClient) Structurize(ctx context.Context, parts []*ai.Part) (providers.StructurizeFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Structurize", ctx, parts)
	ret0, _ := ret[0].(providers.StructurizeFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Structurize indicates an expected call of Structurize.
func (mr *MockLLMClientMockRecorder) Structurize(ctx, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Structurize", reflect.TypeOf((*MockLLMClient)(nil).Structurize), ctx, parts)
}

// StructurizeWithHistory mocks base method.
func (m *MockLLMClient) StructurizeWithHistory(ctx context.Context, history []*ai.Message, parts []*ai.Part) (providers.StructurizeFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructurizeWithHistory", ctx, history, parts)
	ret0, _ := ret[0].(providers.StructurizeFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StructurizeWithHistory indicates an expected call of StructurizeWithHistory.
func (mr *MockLLMClientMockRecorder) StructurizeWithHistory(ctx, history, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructurizeWithHistory", reflect.TypeOf((*MockLLMClient)(nil).StructurizeWithHistory), ctx, history, parts)
}

// Summarize mocks base method.
func (m *MockLLMClient) Summarize(ctx context.Context, parts []*ai.Part) (providers.SummarizeFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, parts)
	ret0, _ := ret[0].(providers.SummarizeFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockLLMClientMockRecorder) Summarize(ctx, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockLLMClient)(nil).Summarize), ctx, parts)
}

// SummarizeWithHistory mocks base method.
func (m *MockLLMClient) SummarizeWithHistory(ctx context.Context, history []*ai.Message, parts []*ai.Part) (providers.SummarizeFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizeWithHistory", ctx, history, parts)
	ret0, _ := ret[0].(providers.SummarizeFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummarizeWithHistory indicates an expected call of SummarizeWithHistory.
func (mr *MockLLMClientMockRecorder) SummarizeWithHistory(ctx, history, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizeWithHistory", reflect.TypeOf((*MockLLMClient)(nil).SummarizeWithHistory), ctx, history, parts)
}

// MockDigitalInkRecognizer is a mock of DigitalInkRecognizer interface.
type MockDigitalInkRecognizer struct {
	ctrl     *gomock.Controller
	recorder *MockDigitalInkRecognizerMockRecorder
	isgomock struct{}
}

// MockDigitalInkRecognizerMockRecorder is the mock recorder for MockDigitalInkRecognizer.
type MockDigitalInkRecognizerMockRecorder struct {
	mock *MockDigitalInkRecognizer
}

// NewMockDigitalInkRecognizer creates a new mock instance.
func NewMockDigitalInkRecognizer(ctrl *gomock.Controller) *MockDigitalInkRecognizer {
	mock := &MockDigitalInkRecognizer{ctrl: ctrl}
	mock.recorder = &MockDigitalInkRecognizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDigitalInkRecognizer) EXPECT() *MockDigitalInkRecognizerMockRecorder {
	return m.recorder
}

// RecognizeInk mocks base method.
func (m *MockDigitalInkRecognizer) RecognizeInk(ctx context.Context, elements []models.Element) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecognizeInk", ctx, elements)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecognizeInk indicates an expected call of RecognizeInk.
func (mr *MockDigitalInkRecognizerMockRecorder) RecognizeInk(ctx, elements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecognizeInk", reflect.TypeOf((*MockDigitalInkRecognizer)(nil).RecognizeInk), ctx, elements)
}
